CREATE TABLE COMCODE (
	CREATED_DT				DATE			NULL		,
	CREATED_USER_ID			VARCHAR2(50)	NULL		,
	CREATED_HOST_IP			VARCHAR2(50)	NULL		,
	CREATED_APP_URL			VARCHAR2(500)	NULL		,
	MODIFIED_DT				DATE		 	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)	NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)	NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	NULL		,  
	SYSTEM_TYPE_CODE		VARCHAR2(3)		NOT NULL 	,      
  	CODE_ID	  	      		VARCHAR2(255) 	NOT NULL 	,
  	CODE					VARCHAR2(255) 	NOT NULL 	,
	CODE_NAME				VARCHAR2(255) 	NOT NULL 	,
	CODE_NAME_ABBR			VARCHAR2(255) 	NULL 		,	
  	P_CODE_ID  		    	VARCHAR2(255)	NULL 		,
	FROM_DT					DATE			NOT NULL	,
	TO_DT					DATE			NOT NULL	,
	HIERARCHY_LEVEL			INT	DEFAULT(1)	NOT NULL	,
	PRT_SEQ					INT				NULL		,		
  	LOW_LEVEL_CODE_LENGTH	INT				NULL		,
	CMT					  	VARCHAR2(2000) 	NULL 		,
	constraint pk_comcode primary key(SYSTEM_TYPE_CODE, CODE_ID)	
); 

COMMENT ON TABLE COMCODE IS '공통코드정보';
COMMENT ON COLUMN COMCODE.CREATED_DT IS '최초등록일시';
COMMENT ON COLUMN COMCODE.CREATED_USER_ID IS '최초등록유저';
COMMENT ON COLUMN COMCODE.CREATED_HOST_IP IS '최초등록IP';
COMMENT ON COLUMN COMCODE.CREATED_APP_URL IS '최초등록APPURL';
COMMENT ON COLUMN COMCODE.MODIFIED_DT IS '최종수정일시';
COMMENT ON COLUMN COMCODE.MODIFIED_USER_ID IS '최종수정유저';
COMMENT ON COLUMN COMCODE.MODIFIED_HOST_IP IS '최종수정IP';
COMMENT ON COLUMN COMCODE.MODIFIED_APP_URL IS '최종수정APPURL';
COMMENT ON COLUMN COMCODE.SYSTEM_TYPE_CODE IS '시스템구분코드';
COMMENT ON COLUMN COMCODE.CODE_ID IS '코드ID';
COMMENT ON COLUMN COMCODE.CODE IS '공통코드';
COMMENT ON COLUMN COMCODE.CODE_NAME IS '코드명';
COMMENT ON COLUMN COMCODE.CODE_NAME_ABBR IS '코드명약어';
COMMENT ON COLUMN COMCODE.P_CODE_ID IS '상위코드ID';
COMMENT ON COLUMN COMCODE.FROM_DT IS '시작일시';
COMMENT ON COLUMN COMCODE.TO_DT IS '종료일시';
COMMENT ON COLUMN COMCODE.HIERARCHY_LEVEL IS '계층단계(1부터 시작)';
COMMENT ON COLUMN COMCODE.PRT_SEQ IS '출력순서';
COMMENT ON COLUMN COMCODE.LOW_LEVEL_CODE_LENGTH IS '하위레벨코드길이';
COMMENT ON COLUMN COMCODE.CMT IS '비고';


CREATE TABLE COMDEPT (
	CREATED_DT			  	DATE				NULL		,
	CREATED_USER_ID			VARCHAR2(50)		NULL		,
	CREATED_HOST_IP			VARCHAR2(50)		NULL		,
	CREATED_APP_URL			VARCHAR2(500)	  	NULL		,
	MODIFIED_DT			  	DATE		    	NULL		,
	MODIFIED_USER_ID		VARCHAR2(50)		NULL		,
	MODIFIED_HOST_IP		VARCHAR2(50)		NULL		,
	MODIFIED_APP_URL		VARCHAR2(500)	  	NULL		,
	DEPT_ID				    VARCHAR2(10) 	  	NOT NULL 	,
	ORG_CD				    VARCHAR2(50)		NULL		,
  	DEPT_CD				    VARCHAR2(10) 	  	NOT NULL 	,
  	P_DEPT_ID			    VARCHAR2(255)	  	NULL 		,
  	DEPT_NM_KOR			  	VARCHAR2(255) 	  	NOT NULL 	,
	DEPT_ABBR_KOR		  	VARCHAR2(255) 	  	NULL 		,
  	DEPT_NM_ENG			  	VARCHAR2(255) 	  	NULL 		,--COMMENT '부서명(영어)',
	DEPT_ABBR_ENG		  	VARCHAR2(255) 	  	NULL 		,--COMMENT '부서약어(영어)',
	FROM_DT				    DATE			  	NULL		,--COMMENT '시작일',
	TO_DT				    DATE			  	NULL		,--COMMENT '종료일',	
	PRT_SEQ				    INT					NULL		,--COMMENT '출력순서',		
	CMT					    VARCHAR(2000) 		NULL 		,--COMMENT '비고',
	constraint pk_comdept 		primary key(DEPT_ID),
	constraint fk_comdept1	 	foreign key(P_DEPT_ID) references COMDEPT(DEPT_ID)
); 

COMMENT ON TABLE COMCODE IS '부서정보';
COMMENT ON COLUMN COMCODE.CREATED_DT IS '최초등록일시';
COMMENT ON COLUMN COMCODE.CREATED_USER_ID IS '최초등록유저';
COMMENT ON COLUMN COMCODE.CREATED_HOST_IP IS '최초등록IP';
COMMENT ON COLUMN COMCODE.CREATED_APP_URL IS '최초등록APPURL';
COMMENT ON COLUMN COMCODE.MODIFIED_DT IS '최종수정일시';
COMMENT ON COLUMN COMCODE.MODIFIED_USER_ID IS '최종수정유저';
COMMENT ON COLUMN COMCODE.MODIFIED_HOST_IP IS '최종수정IP';
COMMENT ON COLUMN COMCODE.MODIFIED_APP_URL IS '최종수정APPURL';

COMMENT ON COLUMN COMCODE.DEPT_ID IS '부서ID';
COMMENT ON COLUMN COMCODE.ORG_CD IS '회사코드';
COMMENT ON COLUMN COMCODE.DEPT_CD IS '부서코드';
COMMENT ON COLUMN COMCODE.P_DEPT_ID IS '상위부서ID';
COMMENT ON COLUMN COMCODE.DEPT_NM_KOR IS '부서명(한글)';
COMMENT ON COLUMN COMCODE.DEPT_ABBR_KOR IS '부서약어(한글)';



